# Generated by Django 5.1.6 on 2025-05-08 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='O número tem que ser o formato de: 19 12345-6789', regex='^\\+?1?\\d{9,15}$')])),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Professore',
            },
        ),
        migrations.CreateModel(
            name='Disciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, choices=[('MC', 'Mecatrônica'), ('ADM', 'Administração'), ('ADS', 'Análise e Desenvolvimento de Sistemas'), ('MA', 'Manufatura')], max_length=3, null=True)),
                ('carga_horaria', models.TimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='Ambiente.professor')),
            ],
            options={
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('periodo', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=5)),
                ('sala', models.CharField(max_length=255)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambiente.disciplinar')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambiente.professor')),
            ],
            options={
                'verbose_name': 'Ambiente',
            },
        ),
    ]
